---
title: "Isogeny-based Cryptography Wiki"
subtitle: "A collaborative, accessible reference for isogeny-based cryptographic schemes."
date-modified: ""
---

Welcome to the **Isogeny-based Cryptography Wiki**. This site serves as an open-source, mathematically rigorous, and accessible repository of knowledge detailing post-quantum cryptographic schemes built on the hardness of finding isogenies between elliptic curves.

## Getting Started

If you are not familiar with cryptographic schemes, we recommend [Mike Rosulek's book](https://joyofcryptography.com/). For the underlying mathematics, see [Steven Galbraith's book](https://www.math.auckland.ac.nz/~sgal018/crypto-book/crypto-book.html). You may also benefit from reading PhD theses in this area, for instance [this list](https://github.com/GiacomoPope/maths-theses) curated by Giacomo Pope.

You may also find good reference material in past schools, such as [Bristol 2020](https://isogenyschool2020.co.uk/schedule/), [ANTS 2020](https://www.youtube.com/@ANTSSummerSchool/videos), [PCMI 2022](https://www.youtube.com/playlist?list=PLldN_DpkXL3amFV76Dmimhbrm0MYa4d32), [IPAM 2022](https://www.youtube.com/playlist?list=PLHyI3Fbmv0SdibCMJcJFBZPARwec6fPnQ), [VaNTAGe 2022](https://www.youtube.com/playlist?list=PLo3uxbU5v05z8XnaEeNYI_xbn_IrvgLvJ), [CIMPA 2024](https://www.youtube.com/playlist?list=PLLxG_np9o-2fSsZcOq0woYWBxbiSFy1qI), [SLMath 2024](https://www.slmath.org/summer-schools/1068#schedule_notes), [PQCSA 2025](https://www.youtube.com/playlist?list=PLiHaXFHjrqYcvzIxFEo118XCzxI-KSctT), and [AWS 2026](https://swc-math.github.io/aws/2026/index.html).

To engage with the community, consider joining activities such as the [Isogeny Club](https://isogeny.club/), [Leuven Isogeny Days](https://www.esat.kuleuven.be/cosic/projects/isocrypt/workshops/), [BIRS workshops](https://www.birs.ca/events/2025/5-day-workshops/25w5500), and [Swissogeny Day](https://swissogeny.github.io/).

## Cryptographic Schemes

This wiki aims to cover all peer-reviewed isogeny-based key establishment schemes (key exchange, PKE, KEM, etc.) and digital signature schemes.

**Legend:** []{r=100} torsion points; []{b=100} quaternion algebra; []{g=100} group action;

:::: {.columns}
::: {.column width="50%"}
### Key Establishment

::: {.unlisted-schemes}
- []{r=100} [SIDH](/schemes/key-establishment/sidh.qmd) (2011--2022) 
- []{r=100} [$k$-SIDH](/schemes/key-establishment/ksidh.qmd) (2017--2022) 
- []{g=100} [CSIDH](/schemes/key-establishment/csidh.qmd) (2018) 
- []{r=100} SIDH UM (2018--2022)
- []{r=100} SIAKE (2019--2022)
- []{g=100} AGKE (2019)
- []{g=100} [OSIDH](/schemes/key-establishment/osidh.qmd) (2019)
- []{g=100} [CSURF](/schemes/key-establishment/csurf.qmd) (2020) 
- []{r=100} [B-SIDH](/schemes/key-establishment/bsidh.qmd) (2020--2022) 
- []{r=50 g=50} [SiGamal](/schemes/key-establishment/sigamal.qmd) (2020) 
- []{r=50 g=50} [C-SiGamal](/schemes/key-establishment/csigamal.qmd) (2020)
- []{g=100} $\Pi$-SIDE (2020) 
- []{g=100} $\Pi$-CSIDH (2020) 
- []{r=50 g=50} [SimS](/schemes/key-establishment/sims.qmd) (2021)
- []{g=100} [CSIDH UPKE](/schemes/key-establishment/csidhupke.qmd) (2021)
- []{r=50 b=50} [Séta](/schemes/key-establishment/seta.qmd) (2021--2022) 
- []{r=100} [HealSIDH](/schemes/key-establishment/healsidh.qmd) (2021--2022)
- []{b=100} GA-PAKE (2022)
- []{b=100} [pSIDH](/schemes/key-establishment/psidh.qmd) (2022--2023)
- []{r=100} [M-SIDH](/schemes/key-establishment/msidh.qmd) (2023)
- []{r=100} [MD-SIDH](/schemes/key-establishment/mdsidh.qmd) (2023)
- []{r=100} [FESTA](/schemes/key-establishment/festa.qmd) (2023)
- []{r=100} [binSIDH](/schemes/key-establishment/binsidh.qmd) (2023)
- []{r=100} [terSIDH](/schemes/key-establishment/tersidh.qmd) (2023)
- []{b=100} saPAKE (2023)
- []{b=100} LPKEga (2024)
- []{r=50 b=50} [QFESTA](/schemes/key-establishment/qfesta.qmd) (2024)
- []{r=50 g=50} [TOGA-UE](/schemes/key-establishment/togaue.qmd) (2024)
- []{g=100} [BIN-UE](/schemes/key-establishment/binue.qmd) (2024)
- []{r=50 b=50} [SILBE](/schemes/key-establishment/silbe.qmd) (2024)
- []{r=50 b=50} [POKÉ](/schemes/key-establishment/poke.qmd) (2025)
- []{r=50 b=50} [LIT-SiGamal](/schemes/key-establishment/litsigamal.qmd) (2025)
- []{r=50 b=50} [PIKE](/schemes/key-establishment/pike.qmd) (2026)
:::
:::

::: {.column width="50%"}
### Digital Signature

::: {.unlisted-schemes}
- []{r=100} JS (2014)
- []{r=100} YAJJS (2017)
- []{b=100} GPS (2017) 
- []{g=100} [SeaSign](/schemes/digital-signature/seasign.qmd) (2019)
- []{g=100} [CSI-FiSh](/schemes/digital-signature/csifish.qmd) (2019) 
- []{g=100} Sashimi (2020)
- []{g=100} Lossy CSI-FiSh (2020)
- []{b=100} [SQISign](/schemes/digital-signature/sqisign.qmd) (2020) 
- []{g=100} Calamari (2020)
- []{g=100} FSIBS (2021)
- []{g=100} IAS (2021)
- []{g=100} CSI-RAShi (2021)
- []{g=100} BDKLP (2022)
- []{r=100} SIDH PoK (2022)
- []{g=100} CSI-SharK (2023)
- []{g=100} SCALLOP (2023)
- []{g=100} CJSS (2023)
- []{g=100} CSI-Otter (2023)
- []{g=100} JSD (2024)
- []{g=100} SCALLOP-HD (2024)
- []{r=50 b=50} [SQIsignHD](/schemes/digital-signature/sqisignhd.qmd) (2024)
- []{b=100} AprèsSQI (2024)
- []{r=50 b=50} SQIsign2D-East (2024)
- []{r=50 b=50} SQIsign2D-West (2024)
- []{r=50 b=50} SQIPrime (2024)
- []{r=50 b=50} PIsignHD (2025)
- []{b=100} Erebor (2025)
- []{b=100} Durian (2025)
- []{r=50 b=50} PRISM (2025)
- []{g=100} SDVS (2025)
- []{g=100} PEARL-SCALLOP (2025)
- []{g=100} Tanuki (2025)
- []{r=50 b=50} SQIsign2D$^2$ (2025)
- []{r=50 b=50} SPIDER (2026)
- []{g=100} ORCAS (2026)
- []{g=100} Wombat (2026)
- []{r=50 b=50} SQIsign2DPush (2026)
- []{r=50 b=50} WaterSQI (2026)
- []{r=50 b=50} PRISMO (2026)
- []{r=50 b=50} SQInstructor (2026)
- []{r=50 b=50} SQIAsignHD (2026)
- []{r=100} SPRINT (2026)
:::
:::

::::


## Contributing

This wiki is maintained by the **isogeny-crypto** organization, and contributions are welcome:

- **Spotted an error?** Use the *Report an issue* link on any page, or fix it directly with *Edit this page*.
- **Want to write up a scheme?** Any scheme listed above without a link is waiting for a page. The [contributing guide](https://github.com/isogeny-crypto/isogeny-crypto.github.io/blob/main/CONTRIBUTING.md) walks you through it step by step.
