---
title: "B-SIDH"
subtitle: "Supersingular Isogeny Diffie-Hellman using Twisted Torsion"
date: 2026-06-23
---

## Overview

> Broken by a polynomial time classical algorithm.
 
B-SIDH (pronounced "B-side") is a novel instantiation that significantly improves upon the original [SIDH](/protocols/key-exchange/sidh.qmd) protocol. It bypasses previous restrictions on the shape of the underlying prime field by permitting parties to operate simultaneously within the $(p+1)$-torsion of a supersingular elliptic curve and the $(p-1)$-torsion of its quadratic twist [@bsidh]. 

## Protocol Design

The B-SIDH protocol structurally mimics the traditional SIDH walk-through but instantiates the operations such that Alice and Bob work in opposite quadratic twists using degrees $M$ and $N$, respectively, where $M |(p+1)$ and $N | (p-1)$. 

### Public Parameters
Unlike traditional SIDH, which requires primes of the restrictive form $p = f \cdot 2^a 3^b - 1$ (forcing both parties' smooth degrees to divide $p+1$), B-SIDH selects a prime $p$ such that both $p+1$ and $p-1$ are engineered to be smooth, allowing for significantly smaller primes.

The protocol specifies a starting supersingular curve $E_0 / \mathbb{F}_{p^2}$. It also establishes a basis $\{P_A, Q_A\}$ for the $M$-torsion in $E_0(\mathbb{F}_{p^2})$ and a basis $\{P_B, Q_B\}$ for the $N$-torsion corresponding to the quadratic twist. Because Montgomery arithmetic is twist-agnostic, coordinates from both sets are processed identically using their $x$-coordinates over $\mathbb{F}_{p^2}$.

### Alice's Key Generation
* Alice chooses two secret integers $(\alpha_A, \beta_A) \in \mathbb{Z}/M\mathbb{Z} \times \mathbb{Z}/M\mathbb{Z}$.
* She computes her secret point $S_A = [\alpha_A]P_A + [\beta_A]Q_A$ of order $M$ from the $(p+1)$-torsion.
* She uses $S_A$ to compute her secret $M$-isogeny $\phi_A : E_0 \rightarrow E_A$, where $E_A = E_0 / \langle S_A \rangle$. Because $p+1$ is engineered to be smooth but may contain larger prime factors than traditional SIDH, computing her secret isogeny requires composing walks of multiple prime degrees ($l$-isogenies). Evaluating these larger $l$-isogenies in practice is accelerated using [$\sqrt{élu}$](https://velusqrt.isogeny.org/).
* During the isogeny computation, she maps Bob's basis points $P_B$ and $Q_B$ through $\phi_A$. 
* **Alice's Public Key:** $PK_A = (E_A, \phi_A(P_B), \phi_A(Q_B))$.

### Bob's Key Generation
* Bob chooses two secret integers $(\alpha_B, \beta_B) \in \mathbb{Z}/N\mathbb{Z} \times \mathbb{Z}/N\mathbb{Z}$.
* He computes his secret point $S_B = [\alpha_B]P_B + [\beta_B]Q_B$ of order $N$ from the $(p-1)$-torsion (on the quadratic twist).
* He uses $S_B$ to compute his secret $N$-isogeny $\phi_B : E_0 \rightarrow E_B$, where $E_B = E_0 / \langle S_B \rangle$. Just like Alice, Bob's $N$-isogeny computation involves larger prime factors from $p-1$ and applies the same [$\sqrt{élu}$](https://velusqrt.isogeny.org/).
* During his isogeny computation, he maps Alice's basis points $P_A$ and $Q_A$ through $\phi_B$.
* **Bob's Public Key:** $PK_B = (E_B, \phi_B(P_A), \phi_B(Q_A))$.

### Shared Secret Computation
* **Alice:** Upon receiving $PK_B$, Alice uses her secret integers to compute a new point $S'_A = [\alpha_A]\phi_B(P_A) + [\beta_A]\phi_B(Q_A)$ of order $M$ on curve $E_B$. She computes the $M$-isogeny $\phi'_A: E_B \rightarrow E_B / \langle S'_A \rangle$.
* **Bob:** Upon receiving $PK_A$, Bob uses his secret integers to compute a new point $S'_B = [\alpha_B]\phi_A(P_B) + [\beta_B]\phi_A(Q_B)$ of order $N$ on curve $E_A$. He computes the $N$-isogeny $\phi'_B: E_A \rightarrow E_A / \langle S'_B \rangle$.
* Both parties successfully arrive at the same shared secret by computing the j-invariant of their respective final image curves, as $E_B / \langle S'_A \rangle \cong E_A / \langle S'_B \rangle$.


## Security Assumptions

B-SIDH relies on different security assumptions compared to standard SIDH, primarily because it alters the nature of the isogeny walks.

* **Multiple Edge Sets:** Unlike SIDH, where walks are restricted to a single $l$-isogeny graph, B-SIDH requires switching between multiple $l$-isogeny graphs. Security assumes that navigating multiple edge sets does not weaken the underlying supersingular isogeny problem, as long as the total number of destination nodes remains comparable to SIDH.

* **Full-Length Walks:** The reduction in prime size means that Alice and Bob's secret walks cover nearly the entire graph (almost full-length), compared to the half-length walks in standard SIDH. The complexity of attacks reamins dictated by the supersingular isogeny graph path finding algorithms.

## Progress

TODO